# fly.toml app configuration file generated for ssh-portfolio on 2024-05-08T18:20:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ssh-portfolio'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 2222
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 2222
  auto_stop_machines = true
  auto_start_machines = true

  [[services.ports]]
    port = 22

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
